### ISSUE TITLE
Sticky Checklist on Desktop

### ISSUE THREAD

**Issue by lisaratner** [rossettistone/bizport#229] opened 2016-07-27 23:54 UTC
Sometimes it sticks on the left hand side when you scroll and sometimes it doesn't.
Can we make it always sticky

**Comment by rossettistone** [comment] 2016-07-28 00:39
Unable to reproduce the problem. Can you describe a set of steps that cause it not to stick when scrolling?

**Comment by lisaratner** [comment] 2016-08-05 22:33
hmm, I scrolled and it wasn't sticky haha. I'll try to be more aware.

**Comment by rossettistone** [comment] 2016-08-16 16:52
For now, closing as unreproducable. We can re-open if this recurs and we have reproduction steps.

**Closed** 2016-08-18 17:45 UTC
Labels: bug
